### PR TITLE
WIP: Adding Linux Enumeration Support for 64 bit

### PR DESCRIPTION
**Pull request by nathanjsweet**
1. Adding ioctl calls on usb device to get usage information
2. Adding non-linux default

### CODE REVIEW

**Comment by nathanjsweet** [comment]
I'm still testing this on my own Linux laptop, but so far it looks good. I'll let you know when everything looks good on my end and you can start doing your own testing.
Thanks for this project!

**Comment by marshallbrekka** [comment]
@nathanjsweet looks pretty good, im not opposed to adding this into the u2fhost lib, but what do you think about also trying to get this adding into the hid library its self?

**Comment by nathanjsweet** [comment]
I did a bit of digging, and there's actually no way to get the Usage and UsagePage info on linux without opening the device and making a hid node (thereafter you can make the ioctl calls). That seems like some pretty gross overkill to me. I decided to cheat and use the Product and Manufacturer strings for Linux for now. I also replaced the hid library with the new recommended one. I can confirm that this works on my laptop. Let me know what you think.

**Comment by marshallbrekka** [comment]
@nathanjsweet awesome, I'll test this out on my Mac to verify the new hid lib works as expected.

Regarding checking the usage page, if there is truly no other way to do it, it seems like thats just going to be a requirement for running on linux?

From a users perspective I would image its going to get cumbersome really fast if they have to maintain a list of known manufacturers, rather than being able to rely on hardware detection of the U2F feature.

Also, I would argue that while it might feel like overkill, its not a frequent operation to list devices (only on a challenge operation), so the added bit of overhead is really quite small in the scheme of things.

**Comment by marshallbrekka** [comment]
Ok tried it out, when attempting to open the device im getting `hidapi: unknown failure`, I'll see if I can track down where/why, but it might take me a little  but.

**Comment by nathanjsweet** [comment]
Okay, I added the hid raw api, its able to get the usage for linux via the udev lib.

**Comment by alberts** [comment]
@marshallbrekka would love to get something the lines of this patch merged. what's missing, if anything?

**Comment by Chili-Man** [comment]
@marshallbrekka  @nathanjsweet  anything I can do to help get this merged?  I would like to be able to get this to work https://github.com/segmentio/aws-okta/issues/211

**Comment by marshallbrekka** [comment]
@Chili-Man last time I tried out this branch it failed to pickup my U2F keys on Mac.

All that should be required is making sure it reliably works on both platforms

**Comment by marshallbrekka** [comment]
@Chili-Man the original branch for this PR no longer exists, I was able to push up a [new PR](https://github.com/marshallbrekka/go-u2fhost/pull/5/files), and added a fixed the unreliable device lookup.

Can you try out the [registration cmd](https://github.com/marshallbrekka/go-u2fhost/blob/72b0e7a3f583583996b3b382d2dfaa81fdc4b82c/cmd/register.go) on linux and see if it picks up your U2F device?

```bash
$ ./cmd register --app-id foobar --challenge my-challenge --facet my-facet -v
```

**Comment by Chili-Man** [comment]
thanks @marshallbrekka  I'll try that out. I appreciate the help!

**Comment by marshallbrekka** [comment]
@Chili-Man I was able to do some testing myself on Ubuntu using a VM, and basically hit the same issues as before.

The current linux backend used in hidapi doesn't expose the `Usage` and `UsagePage` fields, which is required to correctly identity U2F devices.
I tried [enabling some codepaths in the libusb](https://github.com/libusb/hidapi/blob/d64f6c6a16ac0468e9066767080c818c995c37b1/libusb/hid.c#L129-L135) hidapi backend that will populate those fields, but libusb requires the end user to add configuration files to allow access to the hid devices (you have to run as root otherwise), which seems pretty user hostile to me.

I was however able to get it working without any user configuration required by switching the hidapi backend to use [hidraw](https://github.com/libusb/hidapi/tree/d64f6c6a16ac0468e9066767080c818c995c37b1/linux), but the backend choice of libusb vs hidraw is currently baked into the [karalabe/hid](https://github.com/karalabe/hid/blob/9c14560f9ee858c43f40b5cd01392b167aacf4e8/hid_enabled.go#L36) library.

When the weekend rolls around I'll do some more research and start a discussion on the https://github.com/karalabe/hid repo about the best course of action.

For what its worth, I went looking for how FireFox handles this, and they use [hidraw](https://github.com/mozilla/authenticator-rs/blob/674fd0b46bd1659973bbf8db5e7a4e819a38b9cb/src/linux/hidraw.rs) on linux, and [uhid](https://github.com/mozilla/authenticator-rs/blob/674fd0b46bd1659973bbf8db5e7a4e819a38b9cb/src/freebsd/uhid.rs) on freebsd.

**Comment by Chili-Man** [comment]
awesome, thanks for looking into this; we appreciate it

**Comment by nathanjsweet** [comment]
Someone else will have to take this over. Closing.

**Pull request closed without merging**
